#!/bin/sh

if hash gofmt 2>/dev/null
then
    IFS='
    '
    for file in `git diff --cached --name-only --diff-filter=ACM | grep '\.go$' | grep -v -E '(vendor|third_party)/'`
    do
        output=`gofmt -w "$file"`
        if test -n "$output"
        then
            echo >&2 "$output"
            exit 1
        fi
        git add "$file"
    done
else
    echo >&2 "gofmt not installed or not in PATH. Not formatting code."
fi

if test -f "${HOME}/dotfiles/overrides/git/pre-commit"
then
    sh "${HOME}/dotfiles/overrides/git/pre-commit"
fi
