if [ -n "${ZSH_DEBUGRC+1}" ]; then
    zmodload zsh/zprof
fi

ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="agnoster"

HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
#DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(encode64 git pip python tmux urltools)

source ${ZSH}/oh-my-zsh.sh
#functions[prompt_git]=""
functions[prompt_hg]=""  # hg is _slow_ regardless of whether you're in a mercurial dir

bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word

alias d=docker
alias k=kubectl

alias ag='ag --path-to-ignore ~/.ignore'
alias ccat='pygmentize -g'

alias vi='nvim'
alias vim='nvim'

if [[ -f "${HOME}/dotfiles/overrides/zsh/zshrc-overrides" ]]
then
    source "${HOME}/dotfiles/overrides/zsh/zshrc-overrides"
fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
